[package]
name = "dxf"
version = "0.2.0"
authors = ["Brett V. Forsgren <brett.forsgren@outlook.com>"]
build = "build/build.rs"
description = "A rust crate for reading and writing DXF and DXB CAD files."
documentation = "https://docs.rs/dxf/"
repository = "https://github.com/IxMilia/dxf-rs"
readme = "README.md"
keywords = ["AutoCAD", "CAD", "DXB", "DXF"]
license = "Apache-2.0"

[dependencies]
byteorder = "1.0.0"
chrono = "0.3.0"
enum_primitive = "0.1.1"
image = "0.14.0"
itertools = "0.6.0"
num = "0.1.37"
time = "0.1.36"
uuid = { version = "0.4.0", features = ["use_std", "v4"] }

[build-dependencies]
xmltree = "0.4.0"

[dev-dependencies]
glob = "0.2.11"
tempdir = "0.3.5"
